name: FKMC
channels:
  - defaults
dependencies:
  - conda
  - python=3.7
  - ipykernel #this makes the env show up in the list of jupyter environments
  - numpy
  - scipy
  - matplotlib
  - munch
  - cachetools
  - termcolor